package store.makejewelry.BE.enums;

public enum OrderStatus {
    INIT ,
    SELLER_RECEIVE ,
    SELLER_SEND ,
    APPROVAL_MANAGER,
    CUSTOMER_RECEIVE,
    PAYMENT,
    PAYMENT_SUCCESSFULLY,
    DESIGNER_RECEIVE,
    DESIGNER_SEND3D ,
    APPROVAL3D_CUSTOMER ,
    MAKER_RECEIVE,
    MAKE_SEND,
    FINISH_ORDER ,
}
